databases:
  - name: pachislot-syusi-db
    databaseName: app_production
    user: ittokunvim

services:
  - type: web
    name: pachislot-syusi
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    domains:
      - pachislot.ittokunvim.net
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pachislot-syusi-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
